#include "stm32f1xx.h"
#include "tim.h"

void TIM_Init(){
  RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_AFIOEN | RCC_APB2ENR_TIM1EN;
  GPIOA->CRH &= ~GPIO_CRH_CNF8;
  GPIOA->CRH |= GPIO_CRH_CNF8_1;

  TIM1->PSC = 79999U;
  TIM1->CCMR1 = TIM_CCMR1_CC2S_1 | TIM_CCMR1_IC1F_3;
  TIM1->CCER = TIM_CCER_CC2P;
  TIM1->SMCR = TIM_SMCR_TS_2 | TIM_SMCR_TS_0;
  TIM1->SMCR |= TIM_SMCR_SMS_2 | TIM_SMCR_SMS_0;
  TIM1->CR1 = TIM_CR1_CEN;
  TIM1->DIER = TIM_DIER_TIE;
}
